### ISSUE TITLE
Tool to get some number of Tweets into a CSV File for reading Tweets

### ISSUE THREAD

**Issue by jtucker430** [SMAPPNYU/smapp-toolkit#3]
From 1/21 Programmer Meetings.  Submitted by Jonathan and Josh

**Comment by yvan** [comment]
what exactly is this? i just noticed these issues.

**Comment by jtucker430** [comment]
Notes from one of our discussion.  So say I have 25 million tweets and I
want to read 200 of them - I want a quick script to read that says "grab X
number of tweets from this collection and dump into a CSV file so I can
read the text of the tweet".  If you have some options to specify date
range (or "from most recent days") and what other fields are in that file
(twitter handle + other bio fields, whether RT, @, etc.) that would be
great.

Thanks!
Josh

On Mon, Mar 14, 2016 at 4:46 PM, Yvan Scher notifications@github.com
wrote:

> what exactly is this? i just noticed these issues.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SMAPPNYU/smapp-toolkit/issues/3#issuecomment-196514982
> .

## 

---

Joshua A. Tucker, New York University
Professor of Politics and (by courtesy) Russian and Slavic Studies
Co-Director, *NYU Social Media and Political Participation Laboratory
http://smapp.nyu.edu/  *
Incoming Director, Jordan Center for the Advanced Study of Russia
http://jordanrussiacenter.org/ (Sept 2016)
Google Scholar Profile
http://scholar.google.com/citations?user=fc0VgPAAAAAJ&hl=en

twitter: @j_a_tucker http://twitter.com/j_a_tucker
homepage: https://wp.nyu.edu/fas-joshuatucker/
blog: _http://www.washingtonpost.com/blogs/monkey-cage/
http://www.washingtonpost.com/blogs/monkey-cage/_
lab: http://smapp.nyu.edu; @SMaPP_NYU http://twitter.com/SMaPP_NYU

---

**Comment by dpenfoldbrown** [comment]
Hey guys,

This is already there. For date range, you'd need a since() and until()
call. For a simple limit on number, limit() will do:

... start a collection...

from datetime import datetime
collection.since(datetime(2016,3,1)).until(datetime.now()).dump_csv("somefile.csv")

or

collection.limit(200).dump_csv("otherfile.csv")

To specify custom fields in the CSV output, can pass a list of "columns"
(must be valid tweet fields) to dump_csv:

collection.limit(200).dump_csv("finalfile.csv", columns=['id_str',
'user.screen_name', 'timestamp', 'text'])

(The columns I pasted there are the defaults. As you can see, to access
nested fields, such as user fields, add dots. User description would be
"user.description").
